
swagger: '2.0'
info:
  version: "1"
  title: S-CAR API
  description: S-CAR API for scar.ua. URL https://scarapp.herokuapp.com
  
schemes:
  - https
basePath: /v1
paths:
  
    
  /v1/spareparts/id:

    
    get:

      description: |
        Returns SparePart  object if you get it's id
        
          
      responses:
        200:
          description: OK
          schema:
                 title: Sparepart
                 type: object
                 properties:
                   id:
                     type: number
                   articleNumber:
                     type: integer
                   name:
                     type: string
                   producer:
                     type: string
                   price:
                     type: number
                   availability:
                     type: string


                    
              
        default:
          description: Unexpected error
          
          schema:
           title: Error
           type: object
           properties:
             code: 
               type: string
             message:
               type: string
   
    
  /v1/spareparts:
    get:
      description:  Returns content of spareparts objects (array) and info about pages. If **articleNumber** is specified, returns only the objects that has the same articleNumber or includes a part of the number ( starting from the first element) ***None of params are required.***
        
      parameters:
        -
          name: page
          in: query
          description: The number of page. List of objects is divided
           into pages according to a size param. ***Default = 0***
          required: false
          type: number
          format: int
          
        -
          name: size
          in: query
          description: The size of elements to be in this array of objects. ***Default = 30***
          required: false
          type: integer
        -
          name: articleNumber
          in: query
          description: Number of sparepart
          required: false
          type: integer
        -
          name: producer
          in: query
          description: Producer of sparepart
          required: false
          type: string


      responses:
      
        200:
          description: OK
          schema:
           title: ContentAndPageInfo
           type: array
           items:
               title: Content
               type: array
               items:
                 title: Sparepart
                 type: object
                 properties:
                   id:
                     type: number
                   articleNumber:
                     type: integer
                   name:
                     type: string
                   producer:
                     type: string
                   price:
                     type: number
                   availability:
                     type: string


                    
              
        default:
          description: Unexpected error
          
          schema:
           title: Error
           type: object
           properties:
             code: 
               type: string
             message:
               type: string
    
  /v1/producers:
    get:
      description: Returns **Producers** who have Spareparts with specified articleNumber (or a part of the number)
      parameters:
        -
          name: articleNumber
          in: query
          description: Number of sparepart
          required: true
          type: integer
      responses:
      
        200:
          description: OK
          schema:
           title: Producers
           type: array
           items:
               title: Producer
               type: object
               properties:
                   producer:
                     type: string
        default:
          description: Unexpected error
          
          schema:
           title: Error
           type: object
           properties:
             code: 
               type: string
             message:
               type: string
      
   


 

  
